### PR TITLE
implement dark / light toggle

### PR DESCRIPTION
**Pull request by tfenster**

### CODE REVIEW

**Comment by StefanScherer** [comment]
Thank you @tfenster
I tried exactly that yesterday and it worked exactly only once for me. I then checked the settings.json and the schemes array was empty. With procmon I saw that Windows Terminal immediately writes(!) the settings.json again. Maybe WT reads ghe newly opened file and tries to „fix“ it. Interesting that the with wsl sed command it does not happen. 
After trying this and that I committed my wsl.exe workaround. 
But your PR forces me to learn why this happens and how to fix it.

**Comment by tfenster** [comment]
Very weird. It worked for me yesterday for a couple of times, but now it is broken as well. I have implemented [this](https://github.com/tfenster/somethinglikedotfiles/commit/4c4973ba29be77746fcd1175d7d64bc8bf263fac) as workaround, but that breaks compatibility with PowerShell 5.1. Do you mind that?

**Comment by StefanScherer** [comment]
At least this was what I could find out with the original `t` function. Windows Terminal gets a SHARING_VIOLATION and then it writes the settings.json. Maybe it's a but in WT where it forgets about the schemes array.

wt-overwrite-settings-after-change

I'll look into your change later today and try it out if it works better. I'll also make a procmon trace of the WSL `sed` change which seems to work stable.

**Comment by tfenster** [comment]
The other issue with the replace based implementation is that it only works if you already have a colorScheme set up. If the default is still in place, it won't do anything. This could be considered a corner case or solved by e.g. adding a default config with the colorScheme already set up, but this way works quite well for me :)

**Pull request closed without merging**
